version: '3.1'
services :
#  app:
#    build:
#      context: .
#    ports:
#      - 5005:5005
#      - 8081:8081
#    volumes:
#      - .:/app
#    command: [ "gradle", "bootRun" ]
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh run.sh
    ports:
      - 8081:8080
    networks:
      - local
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: db_book
    networks:
      - local
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 1234:8080
    networks:
      - local

#Docker Networks
networks:
  local:
    driver: bridge